[build]
builder = "nixpacks"
buildCommand = "dotnet publish -c Release -o out"

[build.environment]
DOTNET_VERSION = "8.0.100"

[deploy]
startCommand = "dotnet out/CurrencyConverter.dll --urls=http://0.0.0.0:$PORT"

[[services]]
name = "web"
[[services.ports]]
port = 8080
