[build]
builder = "nixpacks"
buildCommand = "DOTNET_VERSION=8.0.100 nixpacks build ."

[build.environment]
DOTNET_VERSION = "8.0.100"

[deploy]
startCommand = "dotnet CurrencyConverter.dll --urls=http://0.0.0.0:$PORT"

[[services]]
name = "web"
[[services.ports]]
port = 8080
